// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function EditItemName(arg1:number,arg2:string):Promise<void>;

export function ExportItems():Promise<string>;

export function GetAllItems():Promise<Array<main.ItemEntry>>;

export function GetFilteredItems():Promise<Array<string>>;

export function GetItemsPage(arg1:number,arg2:number):Promise<main.ItemsResponse>;

export function GetStats():Promise<main.GameStats>;

export function LoadProfile(arg1:string):Promise<void>;

export function ResetKills():Promise<void>;

export function SaveCurrentProfile():Promise<void>;

export function SetItemsPerPage(arg1:number):Promise<number>;

export function SetShowAllItems(arg1:boolean):Promise<boolean>;

export function SwitchProfile(arg1:string):Promise<void>;

export function ToggleFilters():Promise<boolean>;
