// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function EditItemName(arg1, arg2) {
  return window['go']['main']['App']['EditItemName'](arg1, arg2);
}

export function ExportItems() {
  return window['go']['main']['App']['ExportItems']();
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetFilteredItems() {
  return window['go']['main']['App']['GetFilteredItems']();
}

export function GetItemLists() {
  return window['go']['main']['App']['GetItemLists']();
}

export function GetItemsPage(arg1, arg2) {
  return window['go']['main']['App']['GetItemsPage'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function ResetKills() {
  return window['go']['main']['App']['ResetKills']();
}

export function SaveCurrentProfile() {
  return window['go']['main']['App']['SaveCurrentProfile']();
}

export function SetItemsPerPage(arg1) {
  return window['go']['main']['App']['SetItemsPerPage'](arg1);
}

export function SetShowAllItems(arg1) {
  return window['go']['main']['App']['SetShowAllItems'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function ToggleFilters() {
  return window['go']['main']['App']['ToggleFilters']();
}
